export const legal = [
"Administration de l'État",
"Association loi 1901 ou assimilé",
"Assujetti unique à la TVA",
"Autre groupement de droit privé non doté de la personnalité morale",
"Autre personne morale de droit privé",
"Autre personne morale de droit privé inscrite au registre du commerce et des sociétés",
"Autre personne morale de droit public administratif",
"Caisse d'épargne et de prévoyance",
"Collectivité territoriale",
"Comité d'entreprise",
"Entrepreneur individuel",
"Etablissement public administratif",
"Etablissement public ou régie à caractère industriel ou commercial",
"Fiducie",
"Fondation",
"Groupement d'intérêt économique",
"Indivision",
"Organisme de placement collectif en valeurs mobilières sans personnalité morale",
"Organisme de retraite à adhésion non obligatoire",
"Organisme gérant un régime de protection sociale à adhésion obligatoire",
"Organisme mutualiste",
"Organisme professionnel",
"Paroisse hors zone concordataire",
"Personne morale de droit étranger, immatriculée au RCS (registre du commerce et des sociétés)",
"Personne morale de droit étranger, non immatriculée au RCS",
"Société anonyme à conseil d'administration",
"Société anonyme à directoire",
"Société civile",
"Société coopérative agricole",
"Société coopérative commerciale particulière",
"Société créée de fait",
"Société d'assurance mutuelle",
"Société en commandite",
"Société en nom collectif",
"Société en participation",
"Société européenne",
"Société par actions simplifiée",
"Société à responsabilité limitée (SARL)",
"Syndicat de propriétaires"
];
